/**
 * Worker-thread sandbox for executing untrusted JavaScript skill / tool code.
 *
 * The default `new Function()` / `new AsyncFunction()` runs in the main
 * Electron process and has full access to its `require` graph, file system,
 * database, network, etc. That is unsafe for any code originating from the
 * marketplace, generated by an agent, or supplied by the user without an
 * explicit "trusted" flag.
 *
 * This module spawns a fresh Node `worker_threads` Worker per invocation:
 *
 *  - workerData carries the function source + the single `input` argument.
 *  - The worker compiles the source via `new AsyncFunction("input", code)`
 *    and posts the result (or error) back to the parent.
 *  - The worker is given no access to `parentPort`-via-channels, no eval
 *    permission to require Electron-only modules, and is killed after a
 *    hard timeout regardless of result.
 *
 * Limitations (intentional, not bugs):
 *  - The sandboxed code can still `require()` Node built-ins like `fs`,
 *    `child_process`, etc. A full capability-restricted sandbox needs either
 *    an external process with stripped permissions or a VM-based isolate
 *    (vm2 is unmaintained; isolated-vm requires native compilation). This
 *    module is a *process-isolation* sandbox: a crash, hang, or memory
 *    blowup in the worker cannot take down the renderer or main process,
 *    and the worker terminates after `timeoutMs`.
 *  - For stronger isolation, layer a child-process / container sandbox on
 *    top of this — the API stays the same.
 */

import { Worker } from "node:worker_threads";
import path from "node:path";
import log from "electron-log";

const logger = log.scope("function_sandbox");

export interface SandboxRunOptions {
  /** Hard time limit before the worker is terminated. Defaults to 5 s. */
  timeoutMs?: number;
  /** Optional human-readable label for log lines. */
  label?: string;
}

export interface SandboxResult {
  ok: boolean;
  output?: unknown;
  error?: string;
  durationMs: number;
  timedOut: boolean;
}

/**
 * The worker source is inlined as a string so we don't depend on the bundler
 * emitting a separate worker chunk. The worker only knows how to:
 *   1. Build an AsyncFunction from `code`
 *   2. Invoke it with `input`
 *   3. Post the JSON-serializable result back
 */
const WORKER_SOURCE = `
const { parentPort, workerData } = require("node:worker_threads");

(async () => {
  try {
    const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
    const fn = new AsyncFunction("input", workerData.code);
    const result = await fn(workerData.input);
    parentPort.postMessage({ ok: true, result });
  } catch (err) {
    parentPort.postMessage({
      ok: false,
      error: err && err.message ? String(err.message) : String(err),
    });
  }
})();
`;

/**
 * Run untrusted JavaScript code with the given input inside a worker thread.
 *
 * Always resolves — never throws. On timeout the worker is forcibly
 * terminated and the result reports `{ ok: false, timedOut: true }`.
 */
export async function runInSandbox(
  code: string,
  input: unknown,
  options: SandboxRunOptions = {},
): Promise<SandboxResult> {
  const timeoutMs = options.timeoutMs ?? 5_000;
  const label = options.label ?? "anonymous";
  const start = Date.now();

  return new Promise<SandboxResult>((resolve) => {
    let settled = false;
    let worker: Worker | null = null;
    let timer: NodeJS.Timeout | null = null;

    const finish = (res: Omit<SandboxResult, "durationMs">) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      if (worker) {
        // best-effort terminate — fine if already exited
        worker.terminate().catch(() => {});
      }
      resolve({ ...res, durationMs: Date.now() - start });
    };

    try {
      worker = new Worker(WORKER_SOURCE, {
        eval: true,
        workerData: { code, input },
        // No stdin/stdout/stderr piping — keeps untrusted console.log noise
        // out of the main log file unless we explicitly opt in later.
      });
    } catch (err) {
      finish({
        ok: false,
        error: `Failed to spawn sandbox worker: ${(err as Error).message}`,
        timedOut: false,
      });
      return;
    }

    timer = setTimeout(() => {
      logger.warn(`Sandbox [${label}] timed out after ${timeoutMs}ms — terminating worker`);
      finish({ ok: false, error: `Sandbox timeout after ${timeoutMs}ms`, timedOut: true });
    }, timeoutMs);

    worker.once("message", (msg: { ok: boolean; result?: unknown; error?: string }) => {
      if (msg.ok) {
        finish({ ok: true, output: msg.result, timedOut: false });
      } else {
        finish({ ok: false, error: msg.error ?? "Unknown sandbox error", timedOut: false });
      }
    });

    worker.once("error", (err) => {
      finish({ ok: false, error: `Worker error: ${err.message}`, timedOut: false });
    });

    worker.once("exit", (exitCode) => {
      if (!settled) {
        finish({
          ok: false,
          error: `Worker exited unexpectedly (code ${exitCode})`,
          timedOut: false,
        });
      }
    });
  });
}

/**
 * Convenience wrapper that mirrors the legacy `new AsyncFunction(input, code)`
 * signature but routes through the sandbox. Throws on failure so existing
 * call sites can keep their try/catch shape.
 */
export async function runFunctionSandboxed(
  code: string,
  input: unknown,
  options: SandboxRunOptions = {},
): Promise<unknown> {
  const result = await runInSandbox(code, input, options);
  if (!result.ok) {
    throw new Error(result.error ?? "Sandbox execution failed");
  }
  return result.output;
}

// Reference path import to avoid unused-import warnings if future revisions
// move the worker source to an on-disk file.
void path;
