/**
 * Worker-thread sandbox for executing untrusted JavaScript skill / tool code.
 *
 * The default `new Function()` / `new AsyncFunction()` runs in the main
 * Electron process and has full access to its `require` graph, file system,
 * database, network, etc. That is unsafe for any code originating from the
 * marketplace, generated by an agent, or supplied by the user without an
 * explicit "trusted" flag.
 *
 * This module spawns a fresh Node `worker_threads` Worker per invocation:
 *
 *  - workerData carries the function source + the single `input` argument.
 *  - The worker compiles the source via `new AsyncFunction("input", code)`
 *    and posts the result (or error) back to the parent.
 *  - The worker is given no access to `parentPort`-via-channels, no eval
 *    permission to require Electron-only modules, and is killed after a
 *    hard timeout regardless of result.
 *
 * Limitations (intentional, not bugs):
 *  - The sandboxed code is denied `require(...)` of any module not in the
 *    `allowedModules` allow-list (empty by default), and the ambient
 *    `require`/`process`/`module` globals are shadowed + scrubbed. The one
 *    residual escape is dynamic `import()`, which is syntactic and cannot be
 *    stripped from an in-process worker. For *fully* untrusted marketplace
 *    code, layer the container-isolated path (`JcnJobExecutor` Docker mode)
 *    on top — the API stays the same. This module is a hardened
 *    *process-isolation* sandbox: a crash, hang, memory blowup, or blocked
 *    `require` in the worker cannot take down the renderer or main process,
 *    and the worker terminates after `timeoutMs` / `maxMemoryMb`.
 */

import { Worker } from "node:worker_threads";
import path from "node:path";
import log from "electron-log";

const logger = log.scope("function_sandbox");

export interface SandboxRunOptions {
  /** Hard time limit before the worker is terminated. Defaults to 5 s. */
  timeoutMs?: number;
  /** Optional human-readable label for log lines. */
  label?: string;
  /**
   * Allow-list of module names the sandboxed code may `require(...)`. Anything
   * not in this list (including `fs`, `child_process`, `net`, …) is **denied**
   * by default — the list is empty unless you opt specific modules in.
   */
  allowedModules?: string[];
  /**
   * Hard cap on the worker's V8 old-generation heap (MiB). The worker is torn
   * down if it exceeds this. Defaults to 128 MiB.
   */
  maxMemoryMb?: number;
}

export interface SandboxResult {
  ok: boolean;
  output?: unknown;
  error?: string;
  durationMs: number;
  timedOut: boolean;
}

/**
 * The worker source is inlined as a string so we don't depend on the bundler
 * emitting a separate worker chunk. The worker:
 *   1. Captures `parentPort` before scrubbing globals.
 *   2. Builds a **guarded `require`** that only resolves allow-listed modules.
 *   3. Compiles `code` as an AsyncFunction whose parameters *shadow* the
 *      dangerous ambient identifiers (`require`, `process`, `module`, …) with
 *      neutered values, then best-effort scrubs the real globals so the
 *      `Function("return process")()` escape hatch is closed too.
 *   4. Invokes it with `input` and posts the JSON-serializable result back.
 *
 * Defence-in-depth, not a perfect jail: dynamic `import()` is syntactic and
 * cannot be removed from this in-process worker. For *fully* untrusted
 * marketplace code, prefer the container-isolated path
 * (`JcnJobExecutor` Docker mode). This worker guarantees process isolation,
 * a require allow-list, a hard timeout, and a heap cap.
 */
const WORKER_SOURCE = `
const { parentPort, workerData } = require("node:worker_threads");

(async () => {
  // Capture the real require BEFORE we scrub it, then build a guarded one
  // that only resolves explicitly allow-listed module names.
  const realRequire = require;
  const allowed = new Set(Array.isArray(workerData.allowedModules) ? workerData.allowedModules : []);
  const guardedRequire = (name) => {
    if (!allowed.has(name)) {
      throw new Error("require('" + String(name) + "') is blocked by the sandbox policy");
    }
    return realRequire(name);
  };

  // Best-effort scrub of the global escape hatches. Param shadowing (below)
  // is the primary control; this closes \`Function("return process")()\`.
  try { Object.defineProperty(globalThis, "process", { value: undefined, configurable: true }); } catch (e) {}
  try { delete globalThis.require; } catch (e) {}

  try {
    const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
    // Each ambient identifier is a parameter, so references inside the user
    // code resolve to our neutered/guarded values instead of the real globals.
    const fn = new AsyncFunction(
      "input",
      "require",
      "process",
      "module",
      "__dirname",
      "__filename",
      "global",
      workerData.code,
    );
    const result = await fn(
      workerData.input,
      guardedRequire,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
    );
    parentPort.postMessage({ ok: true, result });
  } catch (err) {
    parentPort.postMessage({
      ok: false,
      error: err && err.message ? String(err.message) : String(err),
    });
  }
})();
`;

/**
 * Run untrusted JavaScript code with the given input inside a worker thread.
 *
 * Always resolves — never throws. On timeout the worker is forcibly
 * terminated and the result reports `{ ok: false, timedOut: true }`.
 */
export async function runInSandbox(
  code: string,
  input: unknown,
  options: SandboxRunOptions = {},
): Promise<SandboxResult> {
  const timeoutMs = options.timeoutMs ?? 5_000;
  const label = options.label ?? "anonymous";
  const allowedModules = options.allowedModules ?? [];
  const maxMemoryMb = options.maxMemoryMb ?? 128;
  const start = Date.now();

  return new Promise<SandboxResult>((resolve) => {
    let settled = false;
    let worker: Worker | null = null;
    let timer: NodeJS.Timeout | null = null;

    const finish = (res: Omit<SandboxResult, "durationMs">) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      if (worker) {
        // best-effort terminate — fine if already exited
        worker.terminate().catch(() => {});
      }
      resolve({ ...res, durationMs: Date.now() - start });
    };

    try {
      worker = new Worker(WORKER_SOURCE, {
        eval: true,
        workerData: { code, input, allowedModules },
        // Cap the worker's heap so a memory-bomb skill is torn down instead of
        // exhausting the host. The thread is also killed after `timeoutMs`.
        resourceLimits: { maxOldGenerationSizeMb: maxMemoryMb },
        // No stdin/stdout/stderr piping — keeps untrusted console.log noise
        // out of the main log file unless we explicitly opt in later.
      });
    } catch (err) {
      finish({
        ok: false,
        error: `Failed to spawn sandbox worker: ${(err as Error).message}`,
        timedOut: false,
      });
      return;
    }

    timer = setTimeout(() => {
      logger.warn(`Sandbox [${label}] timed out after ${timeoutMs}ms — terminating worker`);
      finish({ ok: false, error: `Sandbox timeout after ${timeoutMs}ms`, timedOut: true });
    }, timeoutMs);

    worker.once("message", (msg: { ok: boolean; result?: unknown; error?: string }) => {
      if (msg.ok) {
        finish({ ok: true, output: msg.result, timedOut: false });
      } else {
        finish({ ok: false, error: msg.error ?? "Unknown sandbox error", timedOut: false });
      }
    });

    worker.once("error", (err) => {
      finish({ ok: false, error: `Worker error: ${err.message}`, timedOut: false });
    });

    worker.once("exit", (exitCode) => {
      if (!settled) {
        finish({
          ok: false,
          error: `Worker exited unexpectedly (code ${exitCode})`,
          timedOut: false,
        });
      }
    });
  });
}

/**
 * Convenience wrapper that mirrors the legacy `new AsyncFunction(input, code)`
 * signature but routes through the sandbox. Throws on failure so existing
 * call sites can keep their try/catch shape.
 */
export async function runFunctionSandboxed(
  code: string,
  input: unknown,
  options: SandboxRunOptions = {},
): Promise<unknown> {
  const result = await runInSandbox(code, input, options);
  if (!result.ok) {
    throw new Error(result.error ?? "Sandbox execution failed");
  }
  return result.output;
}

// Reference path import to avoid unused-import warnings if future revisions
// move the worker source to an on-disk file.
void path;
