CREATE TABLE `training_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`base_model_id` text NOT NULL,
	`method` text NOT NULL,
	`status` text DEFAULT 'queued' NOT NULL,
	`progress` integer DEFAULT 0 NOT NULL,
	`current_epoch` integer DEFAULT 0,
	`total_epochs` integer,
	`current_step` integer,
	`total_steps` integer,
	`current_loss` integer,
	`gpu_memory_used_mb` integer,
	`dataset_id` text,
	`dataset_path` text,
	`output_path` text NOT NULL,
	`hyperparameters_json` text,
	`pid` integer,
	`activity_id` text,
	`registry_entry_id` text,
	`error` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`started_at` integer,
	`completed_at` integer
);
