/**
 * Whitehat Manifest — the cryptographically signed "Security Blueprint"
 * shipped with every Sovereign Network repo.
 *
 * Layout:
 *   /whitehat.json   — canonical JSON manifest
 *   /whitehat.sig    — detached JWS produced by the publisher's DID key
 *
 * The manifest declares what the published code is *allowed* to do
 * (file globs, IPC channels, MCP tools, dependency pins). The Verify-Then-Trust
 * pipeline diffs incoming pulls against this manifest before allowing a merge.
 */

import path from "node:path";
import fs from "fs-extra";
import * as crypto from "crypto";

export const WHITEHAT_MANIFEST_FILE = "whitehat.json";
export const WHITEHAT_SIGNATURE_FILE = "whitehat.sig";
export const WHITEHAT_MANIFEST_VERSION = 1;

export interface WhitehatPolicy {
  /** File globs the repo is allowed to contain (relative, POSIX-style). */
  allowedFileGlobs: string[];
  /** File globs that, if present, MUST be flagged. */
  disallowedFileGlobs: string[];
  /** IPC channels the published code may invoke. */
  allowedIpcChannels: string[];
  /** MCP tool names the published code may call. */
  allowedMcpTools: string[];
  /** Dependency pins (`name@semver-or-exact`). */
  dependencyPins: string[];
  /** Maximum on-disk size in MB. 0 = no limit. */
  maxSizeMb: number;
}

export interface WhitehatManifest {
  version: number;
  rid: string;
  name: string;
  description?: string;
  creatorDid: string;
  /** ISO 8601 generation timestamp. */
  generatedAt: string;
  /** SHA-256 of the canonical-JSON-stringified contents below. */
  contentHash: string;
  policy: WhitehatPolicy;
  /** Map of relative file path → SHA-256 hex. Generated by walking the tree. */
  fileHashes: Record<string, string>;
  /** Optional list of declared sub-manifests (for monorepos). */
  subManifests?: string[];
}

export interface WhitehatSignatureEnvelope {
  /** Detached JWS — payload is omitted; signers/verifiers re-derive from manifest. */
  signature: string;
  signerDid: string;
  algorithm: "ed25519" | "secp256k1";
  signedAt: string;
}

// =============================================================================
// CANONICAL HASHING
// =============================================================================

/**
 * Stable canonical JSON: sorted keys, no whitespace.
 * Required so the same logical manifest hashes identically on every host.
 */
export function canonicalJsonStringify(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return "[" + value.map(canonicalJsonStringify).join(",") + "]";
  }
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return (
    "{" +
    keys
      .map((k) => JSON.stringify(k) + ":" + canonicalJsonStringify(obj[k]))
      .join(",") +
    "}"
  );
}

export function sha256Hex(input: string | Buffer): string {
  return crypto.createHash("sha256").update(input).digest("hex");
}

/**
 * Compute the manifest's content hash (everything except `contentHash` itself).
 */
export function computeManifestHash(
  manifest: Omit<WhitehatManifest, "contentHash">
): string {
  return sha256Hex(canonicalJsonStringify(manifest));
}

// =============================================================================
// DEFAULT POLICY
// =============================================================================

export function defaultPolicy(): WhitehatPolicy {
  return {
    allowedFileGlobs: [
      "src/**",
      "public/**",
      "assets/**",
      "package.json",
      "package-lock.json",
      "pnpm-lock.yaml",
      "tsconfig*.json",
      "README.md",
      "LICENSE",
      "*.md",
    ],
    disallowedFileGlobs: [
      "**/.env",
      "**/.env.*",
      "**/id_rsa",
      "**/*.pem",
      "**/secrets/**",
      "**/.aws/**",
      "**/.ssh/**",
    ],
    allowedIpcChannels: [],
    allowedMcpTools: [],
    dependencyPins: [],
    maxSizeMb: 500,
  };
}

// =============================================================================
// FILE-TREE WALK
// =============================================================================

/**
 * Files (and directories) we never include in the manifest hash.
 * These are local-only or trivially derived from source.
 */
const ALWAYS_IGNORE = new Set([
  ".git",
  ".radicle",
  "node_modules",
  ".vite",
  ".turbo",
  "dist",
  "build",
  "out",
  ".next",
  ".cache",
  WHITEHAT_SIGNATURE_FILE,
]);

async function walkRepo(
  root: string,
  current: string,
  acc: Record<string, string>,
  totalBytes: { value: number }
): Promise<void> {
  const entries = await fs.readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    if (ALWAYS_IGNORE.has(entry.name)) continue;
    const abs = path.join(current, entry.name);
    if (entry.isDirectory()) {
      await walkRepo(root, abs, acc, totalBytes);
    } else if (entry.isFile()) {
      const rel = path
        .relative(root, abs)
        .split(path.sep)
        .join("/");
      // Don't hash the manifest itself — it embeds the hash table.
      if (rel === WHITEHAT_MANIFEST_FILE) continue;
      const buf = await fs.readFile(abs);
      totalBytes.value += buf.length;
      acc[rel] = sha256Hex(buf);
    }
  }
}

// =============================================================================
// GENERATION
// =============================================================================

export interface GenerateManifestParams {
  repoRoot: string;
  rid: string;
  name: string;
  description?: string;
  creatorDid: string;
  policy?: Partial<WhitehatPolicy>;
}

/**
 * Walk the working tree at `repoRoot` and produce a fully-populated manifest.
 * Throws if the tree exceeds policy.maxSizeMb.
 */
export async function generateManifest(
  params: GenerateManifestParams
): Promise<WhitehatManifest> {
  const policy: WhitehatPolicy = { ...defaultPolicy(), ...params.policy };

  const fileHashes: Record<string, string> = {};
  const totalBytes = { value: 0 };
  await walkRepo(params.repoRoot, params.repoRoot, fileHashes, totalBytes);

  const sizeMb = totalBytes.value / (1024 * 1024);
  if (policy.maxSizeMb > 0 && sizeMb > policy.maxSizeMb) {
    throw new Error(
      `Repo size ${sizeMb.toFixed(1)}MB exceeds policy limit ${policy.maxSizeMb}MB`
    );
  }

  const partial: Omit<WhitehatManifest, "contentHash"> = {
    version: WHITEHAT_MANIFEST_VERSION,
    rid: params.rid,
    name: params.name,
    description: params.description,
    creatorDid: params.creatorDid,
    generatedAt: new Date().toISOString(),
    policy,
    fileHashes,
  };

  return { ...partial, contentHash: computeManifestHash(partial) };
}

// =============================================================================
// I/O
// =============================================================================

export async function writeManifest(
  repoRoot: string,
  manifest: WhitehatManifest,
  envelope: WhitehatSignatureEnvelope
): Promise<void> {
  await fs.writeFile(
    path.join(repoRoot, WHITEHAT_MANIFEST_FILE),
    canonicalJsonStringify(manifest) + "\n",
    "utf8"
  );
  await fs.writeFile(
    path.join(repoRoot, WHITEHAT_SIGNATURE_FILE),
    JSON.stringify(envelope, null, 2) + "\n",
    "utf8"
  );
}

export async function readManifest(
  repoRoot: string
): Promise<{ manifest: WhitehatManifest; envelope: WhitehatSignatureEnvelope } | null> {
  const manifestPath = path.join(repoRoot, WHITEHAT_MANIFEST_FILE);
  const sigPath = path.join(repoRoot, WHITEHAT_SIGNATURE_FILE);
  if (!(await fs.pathExists(manifestPath)) || !(await fs.pathExists(sigPath))) {
    return null;
  }
  const manifest = (await fs.readJson(manifestPath)) as WhitehatManifest;
  const envelope = (await fs.readJson(sigPath)) as WhitehatSignatureEnvelope;
  return { manifest, envelope };
}

// =============================================================================
// SIGN / VERIFY (ed25519 — reuses node:crypto)
// =============================================================================

/**
 * Sign a manifest with an ed25519 private key (PKCS#8 DER, hex-encoded — same
 * format as `did_document_service.createIdentity` returns).
 *
 * Returns a base64url detached signature over `manifest.contentHash`.
 */
export function signManifest(params: {
  manifest: WhitehatManifest;
  privateKeyHex: string;
  signerDid: string;
}): WhitehatSignatureEnvelope {
  const privateKeyBuffer = Buffer.from(params.privateKeyHex, "hex");
  const privateKey = crypto.createPrivateKey({
    key: privateKeyBuffer,
    format: "der",
    type: "pkcs8",
  });
  const signature = crypto
    .sign(null, Buffer.from(params.manifest.contentHash, "hex"), privateKey)
    .toString("base64");
  return {
    signature,
    signerDid: params.signerDid,
    algorithm: "ed25519",
    signedAt: new Date().toISOString(),
  };
}

/**
 * Verify a manifest envelope. Returns false on any tampering or signature
 * mismatch.
 */
export function verifyManifest(params: {
  manifest: WhitehatManifest;
  envelope: WhitehatSignatureEnvelope;
  publicKeyHex: string;
}): boolean {
  // 1. Re-derive contentHash and compare.
  const partial: Omit<WhitehatManifest, "contentHash"> = {
    version: params.manifest.version,
    rid: params.manifest.rid,
    name: params.manifest.name,
    description: params.manifest.description,
    creatorDid: params.manifest.creatorDid,
    generatedAt: params.manifest.generatedAt,
    policy: params.manifest.policy,
    fileHashes: params.manifest.fileHashes,
    subManifests: params.manifest.subManifests,
  };
  const expectedHash = computeManifestHash(partial);
  if (expectedHash !== params.manifest.contentHash) return false;

  try {
    const publicKey = crypto.createPublicKey({
      key: Buffer.from(params.publicKeyHex, "hex"),
      format: "der",
      type: "spki",
    });
    return crypto.verify(
      null,
      Buffer.from(params.manifest.contentHash, "hex"),
      publicKey,
      Buffer.from(params.envelope.signature, "base64")
    );
  } catch {
    return false;
  }
}
